services:
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure

  zoonavigator:
    image: elkozmon/zoonavigator:1.1.2
    ports:
      - "9000:9000"
    environment:
      HTTP_PORT: 9000
      AUTO_CONNECT_CONNECTION_STRING: zookeeper:2181

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scheduler_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cluster-init:
    build: 
        context: .
        dockerfile: worker-node/Dockerfile
    command: ["java", "-jar", "app.jar", "--spring.profiles.active=init"]
    depends_on:
      - zookeeper
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/scheduler_db
      helix.zookeeper.address: zookeeper:2181
      helix.cluster.name: scheduler-cluster
      scheduler.partitions: 12
      spring.main.web-application-type: none
    restart: on-failure

  helix-controller:
    build: 
        context: .
        dockerfile: worker-node/Dockerfile
    command: ["java", "-jar", "app.jar", "--spring.profiles.active=controller"]
    depends_on:
      zookeeper:
        condition: service_started
      cluster-init:
        condition: service_completed_successfully
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/scheduler_db
      helix.zookeeper.address: zookeeper:2181
      helix.cluster.name: scheduler-cluster
      helix.instance.name: controller-1

  worker-node:
    build: 
        context: .
        dockerfile: worker-node/Dockerfile
    command: ["java", "-jar", "app.jar"]
    restart: on-failure
    depends_on:
      zookeeper:
        condition: service_started
      postgres:
        condition: service_started
      cluster-init:
        condition: service_completed_successfully
      kafka:
        condition: service_started
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/scheduler_db
      helix.zookeeper.address: zookeeper:2181
      helix.cluster.name: scheduler-cluster
      scheduler.partitions: 12
      spring.kafka.bootstrap-servers: kafka:29092

  scheduler-api:
    build: 
        context: .
        dockerfile: scheduler-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      cluster-init:
        condition: service_completed_successfully
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/scheduler_db
      scheduler.partitions: 12

volumes:
  postgres_data:
